# change to list chars of your dataset or use default vietnamese chars
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '

# cpu, cuda, cuda:0
device: 'cuda'

backbone: vgg19_bn

cnn:
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256

seq_modeling: transformer
transformer:  
    d_model: 256
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 2048
    max_seq_length: 1024
    pos_dropout: 0.1
    trans_dropout: 0.1
pretrain: C:\Users\9999\phuoc\ocr\vietocr\results\weights\transformerocr.pth
weights: C:\Users\9999\phuoc\ocr\vietocr\results\weights\transformerocr.pth

optimizer:
    max_lr: 0.0003 
    pct_start: 0.1

trainer:
    batch_size: 32
    print_every: 200
    valid_every: 4000
    iters: 100000
    # where to save our model for prediction
    export: results/weights2/transformerocr.pth
    checkpoint: results/checkpoint2/transformerocr_checkpoint.pth
    log: results/train.log
    # null to disable compute accuracy, or change to number of sample to enable validation while training
    metrics: null

dataset:    
    # name of your dataset
    name: data
    # path to annotation and image
    data_root: C:\Users\9999\phuoc\ocr\vietocr\data\InkData_line_processed
    train_annotation: C:\Users\9999\phuoc\ocr\vietocr\data\valid_InkData_line_processed.txt
    valid_annotation: C:\Users\9999\phuoc\ocr\vietocr\data\valid_InkData_line_processed.txt
    test_annotation: C:\Users\9999\phuoc\ocr\vietocr\data\test_InkData_line_processed.txt
    # resize image to 32 height, larger height will increase accuracy
    image_height: 32
    image_min_width: 32
    image_max_width: 512

dataloader:
    num_workers: 0
    pin_memory: True

aug:
    image_aug: true
    masked_language_model: true

predictor:
    # disable or enable beamsearch while prediction, use beamsearch will be slower
    beamsearch: False

quiet: False 

